apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-a-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-a-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-a-app
  template:
    metadata:
      labels:
        app: tenant-a-app
    spec:
      serviceAccountName: tenant-a-app
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-b-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-b-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-b-app
  template:
    metadata:
      labels:
        app: tenant-b-app
    spec:
      serviceAccountName: tenant-b-app
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
