apiVersion: v1
kind: Namespace
metadata:
  name: secret-demo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-app
  namespace: secret-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrets-app
  name: secrets-app
  namespace: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-app
  template:
    metadata:
      labels:
        app: secrets-app
    spec:
      serviceAccountName: secret-app
      containers:
        - name: secrets-app
          image: public.ecr.aws/aws-cli/aws-cli:2.17.12
          securityContext:
            runAsNonRoot: true
            runAsUser: 1
            allowPrivilegeEscalation: false
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
